const Stellingen = [
  'Accijnzen voor tabak moeten omhoog.',
  'Alleen sigarenboeren/gespecialiseerde zaken mogen nog tabaksproducten verkopen.',
  'Roken in openbare ruimtes is niet meer toegestaan.',
  'Alle voedingsmiddelen krijgen verplicht een gezondheidslabel.',
  'Scholen mogen geen suikerhoudende dranken en ongezonde voeding verkopen.',
  'De suikertaks wordt ingevoerd voor minimaal alle suikerhoudende dranken.',
  'Accijnzen voor alcoholhoudende dranken moeten omhoog.',
  'Alcoholreclame mag pas na 00.00 uur worden uitgezonden.',
  'Zwemlessen worden weer een verplicht onderdeel op basisscholen.',
  'Sporten wordt gratis voor huishoudens met laag inkomen.',
  'Huisvesting van niet-zelfredzame ouderen moet prioriteit krijgen in het bouwprogramma.',
  'Mantelzorgers krijgen meer budget om goede zorg te kunnen verlenen.',
  'Zorgprofessionals krijgen beter uitbetaald.',
  'Er wordt een maximum gesteld aan wat een arts mag verdienen.',
  'Artsen moeten in loondienst komen van de zorginstelling waar ze werken.',
  'Marktwerking in de zorg wordt afgeschaft.',
  'Het eigen risico wordt komende vier jaar afgebouwd.',
  'Medicijnen moeten door Nederlandse bedrijven worden geproduceerd.',
  'Farmaceutische bedrijven mogen niet meer zoveel winst maken.',
  'De overheid moet meer investeren in preventie en zou dit moeten financieren uit de basiszorg.',
  'Basisscholen worden verplicht te onderwijzen over en te ondersteunen in gezonde leefstijlkeuzes.',
  'Een vaccinatieplicht moet worden ingevoerd voor het COVID-19 virus.',
  'Mensen die hun leven als voltooid zien, hebben het recht op euthanasie.',
  'Vrouwen moeten de abortuspil bij hun huisarts kunnen halen.',
  'Vrouwen bepalen zelf wanneer zij in de zwangerschap voor een abortus kiezen.',
  'Er moet meer medisch-wetenschappelijk onderzoek naar voortplantingstechnieken en het voorkomen van ernstige genetische afwijkingen.',
  'Er wordt meer geïnvesteerd in geestelijke gezondheidszorg op wijkniveau.',
  'Verantwoordelijkheid voor jeugdzorg komt bij de Rijksoverheid te liggen.',
  'Gezondheid van mensen moet centraal komen te staan in klimaatbeleid.',
  'Om toekomstige pandemieën door zoönosen (ziektes vanuit dieren) te voorkomen, moet grootschalige veehouderij en fokkerij worden aangepakt.',
];

export default Stellingen;
